version: '3.8'
services:
  mysql-parser-db:
    image: mysql:latest
    container_name: mysql-parser-db-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: parser
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - app-network

  parser-app:
    container_name: parser-app-container
    depends_on:
      - mysql-parser-db
    build: .
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-parser-db:3306/parser
      SPRING_DATASOURCE_USERNAME: bestuser
      SPRING_DATASOURCE_PASSWORD: bestuser
    ports:
      - "8079:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
