package com.example.parser;// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
public class TestitTest3 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testit() {
    driver.get("https://www.w3schools.com/html/html_form_input_types.asp");
    driver.manage().window().setSize(new Dimension(1385, 1103));
    driver.findElement(By.cssSelector("input:nth-child(17)")).click();
    driver.findElement(By.cssSelector("input:nth-child(17)")).sendKeys("Ahntv");
    driver.findElement(By.cssSelector("input:nth-child(20)")).click();
    driver.findElement(By.cssSelector("input:nth-child(20)")).click();
    driver.findElement(By.cssSelector("input:nth-child(20)")).sendKeys("ln");
    driver.findElement(By.id("html")).click();
    driver.findElement(By.id("css")).click();
    {
      WebElement element = driver.findElement(By.id("vehicle1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("vehicle1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("vehicle1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("vehicle1")).click();
    driver.findElement(By.id("vehicle1")).click();
    driver.findElement(By.id("vehicle1")).click();
    driver.findElement(By.id("vehicle3")).click();
    driver.findElement(By.cssSelector("input:nth-child(85)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Hello World!"));
  }
}
